### ISSUE TITLE
Can't interact with the UI on VR

### ISSUE THREAD

**Issue by JTMC-G3** [VerityIncorporated/TooManySuits#2]
Hey! love the mod. i was wondering if you could add some support for VR and the UI. i really enjoy this mod cause if you go to charge and item and there are suits in the way. if you could make some sort of support for VR that would be lovely

Here is the VR repo: https://github.com/DaXcess/LCVR

**Comment by CallMeVerity** [comment]
Unfortunately I do not own any VR headsets and therefore would not be able to implement compatibility. You can implement it yourself and make a pull request if you know how to code.
