### ISSUE TITLE
Mod is spamming errors and doesn't seem to work anymore

### ISSUE THREAD

**Issue by Test-Account666** [VerityIncorporated/TooManySuits#4]
TooManySuits currently spams this error:
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TooManySuits.PluginLoader.Update () (at <434b74dca9584b6891fed93d3e2a47a3>:IL_000E)
```

And no longer provides pages for the suit rack

**Comment by CallMeVerity** [comment]
My friends use this mod while playing, and they said it only shows an error sometimes when leaving games, but it still functions fine.
