### ISSUE TITLE
[Issue] newest suits that purchase from terminal won't add in the rack correctly, will overlap with the original instead

### ISSUE THREAD

**Issue by CoolLKKPS** [VerityIncorporated/TooManySuits#5]
same as topic @VerityIncorporated

**Comment by CoolLKKPS** [comment]
not sure this issues is from this mod btw, maybe more suits, and run with v50

**Comment by CallMeVerity** [comment]
I did some testing with this, it seems to add (for example) the bunny suit, to the second slot in the first rack, it doesn't override anything for me, can you supply a video of this bug please, and how to cause it.

**Comment by CoolLKKPS** [comment]
@VerityIncorporated uh actually, i still working hard for my modpack, so didn't have time really, but with more_suit and this mod, u can easily reproduce this issues, only can reproduce this issue when modded suits are add in the rack

**Comment by CoolLKKPS** [comment]
error that cause text won't appear on top of the rack:
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) HUDManager.DMD<HUDManager::AddPlayerChatMessageClientRpc>(HUDManager,string,int)
HUDManager.__rpc_handler_168728662 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <c4df3e9b25ee4cc28a85022be356d2cd>:0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:36)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass28_0:<wrapCallback>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:136)
AsyncLoggers.Wrappers.JobWrapper:LogWorker() (at ./src/Wrappers/JobWrapper.cs:84)
AsyncLoggers.Wrappers.LogJob:Execute() (at ./src/Wrappers/JobWrapper.cs:68)
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

**Comment by CoolLKKPS** [comment]
@VerityIncorporated ok link here: https://1drv.ms/f/s!AlwrljXcImfClQt9MgB2BOZ-XA9h?e=cX6g0c

**Comment by CoolLKKPS** [comment]
both those issues are happen when play as client

**Comment by CoolLKKPS** [comment]
and when u hot-load a save by using lobbycontrol, toomanysuit won't re-organize the rack

**Comment by CallMeVerity** [comment]
"and when u hot-load a save by using lobbycontrol, toomanysuit won't re-organize the rack" I am unsure what "lobbycontrol" is... I've never supported this.

I've added a manual button which will let you refresh the suit rack, this should solve the problems you're having, if not open up a new issue, thanks!

**Comment by CoolLKKPS** [comment]
@VerityIncorporated when in LAN mode
![image](https://github.com/VerityIncorporated/TooManySuits/assets/96377775/1bf128d8-6baa-4093-90e8-d097a10bf521)
[09:21:07.4876131] [Error  : Unity Log] Trying to add Caret (TMPro.TMP_SelectionCaret) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
[09:21:09.6526320] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TooManySuits.PluginLoader.SetPageText () (at <a999f30347a841f4b25b0e344ff96634>:IL_0000)
TooManySuits.PluginLoader.MoveLeftAction (UnityEngine.InputSystem.InputAction+CallbackContext obj) (at <a999f30347a841f4b25b0e344ff96634>:IL_001C)
UnityEngine.InputSystem.Utilities.DelegateHelpers.InvokeCallbacksSafe[TValue] (UnityEngine.InputSystem.Utilities.CallbackArray\`1[System.Action\`1[TValue]]& callbacks, TValue argument, System.String callbackName, System.Object context) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:IL_001B)
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:36)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass28_0:<wrapCallback>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:136)
AsyncLoggers.Wrappers.JobWrapper:LogWorker() (at ./src/Wrappers/JobWrapper.cs:84)
AsyncLoggers.Wrappers.LogJob:Execute() (at ./src/Wrappers/JobWrapper.cs:68)
Unity.Jobs.JobStruct\`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

[09:21:09.6536353] [Error  : Unity Log] NullReferenceException while executing 'performed' callbacks of '<Unnamed>[/Keyboard/leftArrow]'

**Comment by CoolLKKPS** [comment]
ok i have to test more deeper, will let u know if i really can confirm this issue

**Comment by CallMeVerity** [comment]
I've never tested in LAN mode and I'm unsure why anything would be null since the games LAN mode is just like every other mode.

**Comment by CoolLKKPS** [comment]
this is false issue i think, bc some mod block the update, i can't reproduce again now, but i can confirm another issue which i already created in other issue ticket, in online mode
so this issue only happen when the first launch, and cause by other mod, u should no need to worry about this issue for now
