### ISSUE TITLE
Saving game when on a suit rack page other than 1 breaks suit rack for non-host players on subsequent save loads

### ISSUE THREAD

**Issue by MystPhysX** [VerityIncorporated/TooManySuits#7]
When the host closes a lobby while the suit rack is on a page other than 1 (host side) the suit rack breaks for other players when loading the save in a new lobby. This is broken till the game is restarted.

Seems to be a new bug with the latest update.

**Comment by CallMeVerity** [comment]
I will push an update which sets the suit racks current page number to 0 when a lobby is created, this should resolve the issue you're talking about. If you continue to have this issue in game please contact me on discord (callmeverity) so you can show me the issue in more detail.

**Comment by MystPhysX** [comment]
Does not appear to have solved the issue. I'll message you on Discord shortly.

**Comment by CallMeVerity** [comment]
Sounds good! I'm sorry the potential fix didn't end up working.
