### ISSUE TITLE
All players in server not seeing suit pages.

### ISSUE THREAD

**Issue by Hazard15301** [VerityIncorporated/TooManySuits#8]
I have three PCs in my house with three identical profiles. When I host on mine, the suit pages show up and are functional for me. The other two players do not see the pages. They have the long suit rack that covers up the charging port. If those same players back out and host their own game, the suit pages are visible as expected. I confirmed that the mod works properly as long as there is only 1 player in the server, but anyone that joins after cannot see the suit page dialogue. The suits cover the charging port (depending on how many are installed), so the game is unplayable in most cases.

**Comment by CallMeVerity** [comment]
Recode is being pushed, open a new issue if this issue persists.
